# Added by Rancher RKE2 install script
if [[ -d /var/lib/rancher/rke2/bin  ]];then
    export PATH=$PATH:/var/lib/rancher/rke2/bin
    export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
    source <(kubectl completion bash)
    alias k=kubectl
    complete -o default -F __start_kubectl k
fi
# End
